services:
    website:
        build: .
        environment:
            IGNITION_LOCAL_SITES_PATH: ${PWD}
        volumes:
            - .:/var/www/personal-website
        networks:
            - internal
        depends_on:
            - mysql
    nginx:
        image: nginx:stable-alpine
        restart: unless-stopped
        ports:
            - ${APP_PORT:-80}:80
            - ${SECURE_PORT:-443}:443
            - ${VITE_PORT:-5173}:${VITE_PORT:-5173}
        environment:
            SERVER_NAME: ${SERVER_NAME}
        volumes:
            - .:/var/www/personal-website
            - ./nginx/templates:/etc/nginx/templates
            - ./nginx/ssl-conf:/etc/nginx/ssl-conf
            - ./certbot/www:/var/www/certbot/:ro
            - ./certbot/conf/:/etc/nginx/ssl/:ro
        depends_on:
            - website
        networks:
            - internal
    mysql:
        image: mariadb
        environment:
            MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
            MARIADB_DATABASE: ${DB_DATABASE}
            MARIADB_USER: ${DB_USERNAME}
            MARIADB_PASSWORD: ${DB_PASSWORD}
        volumes:
            - mysql-data:/var/lib/mysql
            - ./mariadb:/etc/mysql/conf.d/
        networks:
            - internal
    certbot:
        image: certbot/certbot
        volumes:
            - ./certbot/www/:/var/www/certbot/:rw
            - ./certbot/conf/:/etc/letsencrypt/:rw
networks:
    internal:
        driver: bridge
volumes:
    mysql-data:
        driver: local
